サインアップ機能
shinonome-inc/backend-final-assignment--Souichirou-Hiyama-Souichirou- pull request #1
Opened 2023-12-24 04:55 UTC by HIyama-1125

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-03-22 05:18 UTC, yota33166 requested changes
よく書けていると思います！
いくつか修正点があるので、確認をお願いします！

2024-03-22 05:18 UTC, yota33166 commented on accounts/views.py
> +        (form.cleaned_data)
(form.cleaned_data)は不要なので消しましょう
何かこのコードを入れた意図があれば教えてください！

2024-03-22 05:18 UTC, yota33166 commented on accounts/tests.py
> +        self.assertIn("このフィールドは必須です。", form.errors["username"])
このテストでは、「既に存在するユーザーを登録するリクエスト」をした際に、ユーザー名の重複を警告するエラーメッセージの確認を行います。そのため、テストの手順として、まずユーザーを作成し、その後に同じユーザー名でリクエストを送信してエラーメッセージを確認する必要があります

2024-03-27 07:23 UTC, yota33166 approved these changes

2024-03-27 07:25 UTC, yota33166 commented
LGTMです！

2024-03-28 12:11 UTC, YusukeKaneko reviewed
とても良くかけていると思います。
少しコメントしました。

2024-03-28 12:11 UTC, YusukeKaneko commented on accounts/tests.py
> +        self.assertFalse(User.objects.filter(username=invalid_data["username"]).exists())
DBのレコードチェックが重複しているので一回で大丈夫です。

2024-03-28 12:11 UTC, YusukeKaneko commented on templates/accounts/signup.html
> +</form>
表示に不要なコメントは削除するかコメントアウトするようにしましょう。

2024-03-28 12:21 UTC, YusukeKaneko commented on accounts/tests.py
> +        self.assertFalse(User.objects.filter(username=invalid_data["username"]).exists())
DBのレコードチェックが重複しているので一回で大丈夫です。

2024-03-28 12:21 UTC, YusukeKaneko commented on templates/accounts/signup.html
> +</form>
表示に不要なコメントは削除するかコメントアウトするようにしましょう。

2024-03-31 13:02 UTC, YusukeKaneko approved these changes

2024-03-31 13:03 UTC, merged